# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spec.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nspec.proto\"\xf6\x01\n\x06Packet\x12\x13\n\x0bpacket_uuid\x18\x01 \x01(\t\x12 \n\x0bpacket_type\x18\x02 \x01(\x0e\x32\x0b.PacketType\x12*\n\x0fnetwork_message\x18\x03 \x01(\x0b\x32\x0f.NetworkMessageH\x00\x12\"\n\x0b\x61\x63k_message\x18\x04 \x01(\x0b\x32\x0b.AckMessageH\x00\x12,\n\x10\x64iscover_message\x18\x05 \x01(\x0b\x32\x10.DiscoverMessageH\x00\x12,\n\x10\x61nnounce_message\x18\x06 \x01(\x0b\x32\x10.AnnounceMessageH\x00\x42\t\n\x07payload\"\x86\x01\n\x0eNetworkMessage\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\r\x12\"\n\x0fsender_location\x18\x03 \x01(\x0b\x32\t.Location\x12\x17\n\x0fmessage_content\x18\x04 \x01(\x0c\x12\x13\n\x0b\x64\x65stination\x18\x05 \x01(\t\"D\n\nAckMessage\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x0f\n\x07node_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\r\"$\n\x0f\x44iscoverMessage\x12\x11\n\ttimestamp\x18\x01 \x01(\r\"W\n\x0f\x41nnounceMessage\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\r\x12 \n\rnode_location\x18\x03 \x01(\x0b\x32\t.Location\"/\n\x08Location\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01*^\n\nPacketType\x12\x13\n\x0fNETWORK_MESSAGE\x10\x00\x12\x0f\n\x0b\x41\x43K_MESSAGE\x10\x01\x12\x14\n\x10\x44ISCOVER_MESSAGE\x10\x02\x12\x14\n\x10\x41NNOUNCE_MESSAGE\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spec_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PACKETTYPE._serialized_start=646
  _PACKETTYPE._serialized_end=740
  _PACKET._serialized_start=15
  _PACKET._serialized_end=261
  _NETWORKMESSAGE._serialized_start=264
  _NETWORKMESSAGE._serialized_end=398
  _ACKMESSAGE._serialized_start=400
  _ACKMESSAGE._serialized_end=468
  _DISCOVERMESSAGE._serialized_start=470
  _DISCOVERMESSAGE._serialized_end=506
  _ANNOUNCEMESSAGE._serialized_start=508
  _ANNOUNCEMESSAGE._serialized_end=595
  _LOCATION._serialized_start=597
  _LOCATION._serialized_end=644
# @@protoc_insertion_point(module_scope)
